/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutMeContent { 'content' : string }
export interface BodyAnalysisSummary {
  'recommendations' : string,
  'muscleMassEstimate' : number,
  'score' : bigint,
  'bodyType' : BodyType,
  'bodyFatPercentage' : bigint,
}
export type BodyType = { 'endomorph' : null } |
  { 'mesomorph' : null } |
  { 'ectomorph' : null };
export interface Booking {
  'id' : string,
  'healthInformation' : string,
  'date' : string,
  'time' : string,
  'user' : Principal,
  'isPaid' : boolean,
  'gymId' : string,
  'healthDisclosureAccepted' : boolean,
  'programId' : string,
}
export interface DonationOption {
  'id' : string,
  'method' : string,
  'details' : string,
}
export interface ExtendedProfile {
  'age' : bigint,
  'bmi' : number,
  'weight' : bigint,
  'height' : bigint,
  'lSit' : bigint,
  'squats' : bigint,
  'pullUps' : bigint,
  'pushUps' : bigint,
  'gender' : string,
  'details' : string,
  'bodyFatPercentage' : number,
}
export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'id' : string,
  'description' : string,
  'image' : ExternalBlob,
}
export interface Gym {
  'id' : string,
  'name' : string,
  'address' : string,
  'details' : string,
}
export interface LifestyleSurveyResult {
  'id' : string,
  'recommendations' : Array<string>,
  'summaryMessage' : string,
  'score' : bigint,
  'category' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TimeSlot {
  'isUnavailable' : boolean,
  'date' : string,
  'time' : string,
  'isBooked' : boolean,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'contactInfo' : string,
  'aboutMe' : string,
  'name' : string,
  'recentTrainings' : Array<string>,
  'isPublic' : boolean,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutProgram {
  'id' : string,
  'title' : string,
  'description' : string,
  'image' : [] | [ExternalBlob],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addDonationOption' : ActorMethod<[DonationOption], undefined>,
  'addGalleryImage' : ActorMethod<[GalleryImage], undefined>,
  'addGym' : ActorMethod<[Gym], undefined>,
  'addWorkoutProgram' : ActorMethod<[WorkoutProgram], undefined>,
  'analyzeBodyShape' : ActorMethod<[string, BodyAnalysisSummary], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<[Booking], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteAnalysisResult' : ActorMethod<[string], undefined>,
  'deleteBooking' : ActorMethod<[string], undefined>,
  'deleteDonationOption' : ActorMethod<[string], undefined>,
  'deleteGalleryImage' : ActorMethod<[string], undefined>,
  'deleteGym' : ActorMethod<[string], undefined>,
  'deleteLifestyleSurveyResult' : ActorMethod<[string], undefined>,
  'deleteWorkoutProgram' : ActorMethod<[string], undefined>,
  'getAboutMeContent' : ActorMethod<[], [] | [AboutMeContent]>,
  'getAllAnalysisResults' : ActorMethod<[], Array<BodyAnalysisSummary>>,
  'getAllLifestyleSurveyResults' : ActorMethod<
    [],
    Array<LifestyleSurveyResult>
  >,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAnalysisResult' : ActorMethod<[string], [] | [BodyAnalysisSummary]>,
  'getAvailableTimeSlots' : ActorMethod<[string], Array<TimeSlot>>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoachProfilePicture' : ActorMethod<[], [] | [ExternalBlob]>,
  'getDonationOptions' : ActorMethod<[], Array<DonationOption>>,
  'getExtendedProfile' : ActorMethod<[Principal], [] | [ExtendedProfile]>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getGyms' : ActorMethod<[], Array<Gym>>,
  'getLifestyleSurveyResult' : ActorMethod<
    [string],
    [] | [LifestyleSurveyResult]
  >,
  'getLikeCount' : ActorMethod<[], bigint>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkoutPrograms' : ActorMethod<[], Array<WorkoutProgram>>,
  'hasCallerLiked' : ActorMethod<[], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'likeWebsite' : ActorMethod<[], undefined>,
  'markBookingAsPaid' : ActorMethod<[string], undefined>,
  'markBookingAsUnpaid' : ActorMethod<[string], undefined>,
  'markTimeSlotUnavailable' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveExtendedProfile' : ActorMethod<[Principal, ExtendedProfile], undefined>,
  'saveLifestyleSurveyResult' : ActorMethod<[LifestyleSurveyResult], undefined>,
  'setAboutMeContent' : ActorMethod<[string], undefined>,
  'setCoachProfilePicture' : ActorMethod<[ExternalBlob], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unmarkTimeSlotUnavailable' : ActorMethod<[string, string], undefined>,
  'updateDonationOption' : ActorMethod<[DonationOption], undefined>,
  'updateGym' : ActorMethod<[Gym], undefined>,
  'updateWorkoutProgram' : ActorMethod<[WorkoutProgram], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];