/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DonationOption = IDL.Record({
  'id' : IDL.Text,
  'method' : IDL.Text,
  'details' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
});
export const Gym = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'details' : IDL.Text,
});
export const WorkoutProgram = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const BodyType = IDL.Variant({
  'endomorph' : IDL.Null,
  'mesomorph' : IDL.Null,
  'ectomorph' : IDL.Null,
});
export const BodyAnalysisSummary = IDL.Record({
  'recommendations' : IDL.Text,
  'muscleMassEstimate' : IDL.Float64,
  'score' : IDL.Nat,
  'bodyType' : BodyType,
  'bodyFatPercentage' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'healthInformation' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'user' : IDL.Principal,
  'isPaid' : IDL.Bool,
  'gymId' : IDL.Text,
  'healthDisclosureAccepted' : IDL.Bool,
  'programId' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AboutMeContent = IDL.Record({ 'content' : IDL.Text });
export const LifestyleSurveyResult = IDL.Record({
  'id' : IDL.Text,
  'recommendations' : IDL.Vec(IDL.Text),
  'summaryMessage' : IDL.Text,
  'score' : IDL.Nat,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'contactInfo' : IDL.Text,
  'aboutMe' : IDL.Text,
  'name' : IDL.Text,
  'recentTrainings' : IDL.Vec(IDL.Text),
  'isPublic' : IDL.Bool,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const TimeSlot = IDL.Record({
  'isUnavailable' : IDL.Bool,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'isBooked' : IDL.Bool,
});
export const ExtendedProfile = IDL.Record({
  'age' : IDL.Nat,
  'bmi' : IDL.Float64,
  'weight' : IDL.Nat,
  'height' : IDL.Nat,
  'lSit' : IDL.Nat,
  'squats' : IDL.Nat,
  'pullUps' : IDL.Nat,
  'pushUps' : IDL.Nat,
  'gender' : IDL.Text,
  'details' : IDL.Text,
  'bodyFatPercentage' : IDL.Float64,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addDonationOption' : IDL.Func([DonationOption], [], []),
  'addGalleryImage' : IDL.Func([GalleryImage], [], []),
  'addGym' : IDL.Func([Gym], [], []),
  'addWorkoutProgram' : IDL.Func([WorkoutProgram], [], []),
  'analyzeBodyShape' : IDL.Func([IDL.Text, BodyAnalysisSummary], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func([Booking], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteAnalysisResult' : IDL.Func([IDL.Text], [], []),
  'deleteBooking' : IDL.Func([IDL.Text], [], []),
  'deleteDonationOption' : IDL.Func([IDL.Text], [], []),
  'deleteGalleryImage' : IDL.Func([IDL.Text], [], []),
  'deleteGym' : IDL.Func([IDL.Text], [], []),
  'deleteLifestyleSurveyResult' : IDL.Func([IDL.Text], [], []),
  'deleteWorkoutProgram' : IDL.Func([IDL.Text], [], []),
  'getAboutMeContent' : IDL.Func([], [IDL.Opt(AboutMeContent)], ['query']),
  'getAllAnalysisResults' : IDL.Func(
      [],
      [IDL.Vec(BodyAnalysisSummary)],
      ['query'],
    ),
  'getAllLifestyleSurveyResults' : IDL.Func(
      [],
      [IDL.Vec(LifestyleSurveyResult)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAnalysisResult' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BodyAnalysisSummary)],
      ['query'],
    ),
  'getAvailableTimeSlots' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TimeSlot)],
      ['query'],
    ),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoachProfilePicture' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getDonationOptions' : IDL.Func([], [IDL.Vec(DonationOption)], ['query']),
  'getExtendedProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ExtendedProfile)],
      ['query'],
    ),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getGyms' : IDL.Func([], [IDL.Vec(Gym)], ['query']),
  'getLifestyleSurveyResult' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(LifestyleSurveyResult)],
      ['query'],
    ),
  'getLikeCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkoutPrograms' : IDL.Func([], [IDL.Vec(WorkoutProgram)], ['query']),
  'hasCallerLiked' : IDL.Func([], [IDL.Bool], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'likeWebsite' : IDL.Func([], [], []),
  'markBookingAsPaid' : IDL.Func([IDL.Text], [], []),
  'markBookingAsUnpaid' : IDL.Func([IDL.Text], [], []),
  'markTimeSlotUnavailable' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveExtendedProfile' : IDL.Func([IDL.Principal, ExtendedProfile], [], []),
  'saveLifestyleSurveyResult' : IDL.Func([LifestyleSurveyResult], [], []),
  'setAboutMeContent' : IDL.Func([IDL.Text], [], []),
  'setCoachProfilePicture' : IDL.Func([ExternalBlob], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unmarkTimeSlotUnavailable' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateDonationOption' : IDL.Func([DonationOption], [], []),
  'updateGym' : IDL.Func([Gym], [], []),
  'updateWorkoutProgram' : IDL.Func([WorkoutProgram], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DonationOption = IDL.Record({
    'id' : IDL.Text,
    'method' : IDL.Text,
    'details' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Gym = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'details' : IDL.Text,
  });
  const WorkoutProgram = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const BodyType = IDL.Variant({
    'endomorph' : IDL.Null,
    'mesomorph' : IDL.Null,
    'ectomorph' : IDL.Null,
  });
  const BodyAnalysisSummary = IDL.Record({
    'recommendations' : IDL.Text,
    'muscleMassEstimate' : IDL.Float64,
    'score' : IDL.Nat,
    'bodyType' : BodyType,
    'bodyFatPercentage' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'healthInformation' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'user' : IDL.Principal,
    'isPaid' : IDL.Bool,
    'gymId' : IDL.Text,
    'healthDisclosureAccepted' : IDL.Bool,
    'programId' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AboutMeContent = IDL.Record({ 'content' : IDL.Text });
  const LifestyleSurveyResult = IDL.Record({
    'id' : IDL.Text,
    'recommendations' : IDL.Vec(IDL.Text),
    'summaryMessage' : IDL.Text,
    'score' : IDL.Nat,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'contactInfo' : IDL.Text,
    'aboutMe' : IDL.Text,
    'name' : IDL.Text,
    'recentTrainings' : IDL.Vec(IDL.Text),
    'isPublic' : IDL.Bool,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const TimeSlot = IDL.Record({
    'isUnavailable' : IDL.Bool,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'isBooked' : IDL.Bool,
  });
  const ExtendedProfile = IDL.Record({
    'age' : IDL.Nat,
    'bmi' : IDL.Float64,
    'weight' : IDL.Nat,
    'height' : IDL.Nat,
    'lSit' : IDL.Nat,
    'squats' : IDL.Nat,
    'pullUps' : IDL.Nat,
    'pushUps' : IDL.Nat,
    'gender' : IDL.Text,
    'details' : IDL.Text,
    'bodyFatPercentage' : IDL.Float64,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addDonationOption' : IDL.Func([DonationOption], [], []),
    'addGalleryImage' : IDL.Func([GalleryImage], [], []),
    'addGym' : IDL.Func([Gym], [], []),
    'addWorkoutProgram' : IDL.Func([WorkoutProgram], [], []),
    'analyzeBodyShape' : IDL.Func([IDL.Text, BodyAnalysisSummary], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func([Booking], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteAnalysisResult' : IDL.Func([IDL.Text], [], []),
    'deleteBooking' : IDL.Func([IDL.Text], [], []),
    'deleteDonationOption' : IDL.Func([IDL.Text], [], []),
    'deleteGalleryImage' : IDL.Func([IDL.Text], [], []),
    'deleteGym' : IDL.Func([IDL.Text], [], []),
    'deleteLifestyleSurveyResult' : IDL.Func([IDL.Text], [], []),
    'deleteWorkoutProgram' : IDL.Func([IDL.Text], [], []),
    'getAboutMeContent' : IDL.Func([], [IDL.Opt(AboutMeContent)], ['query']),
    'getAllAnalysisResults' : IDL.Func(
        [],
        [IDL.Vec(BodyAnalysisSummary)],
        ['query'],
      ),
    'getAllLifestyleSurveyResults' : IDL.Func(
        [],
        [IDL.Vec(LifestyleSurveyResult)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAnalysisResult' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BodyAnalysisSummary)],
        ['query'],
      ),
    'getAvailableTimeSlots' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TimeSlot)],
        ['query'],
      ),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoachProfilePicture' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getDonationOptions' : IDL.Func([], [IDL.Vec(DonationOption)], ['query']),
    'getExtendedProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ExtendedProfile)],
        ['query'],
      ),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getGyms' : IDL.Func([], [IDL.Vec(Gym)], ['query']),
    'getLifestyleSurveyResult' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LifestyleSurveyResult)],
        ['query'],
      ),
    'getLikeCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkoutPrograms' : IDL.Func([], [IDL.Vec(WorkoutProgram)], ['query']),
    'hasCallerLiked' : IDL.Func([], [IDL.Bool], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'likeWebsite' : IDL.Func([], [], []),
    'markBookingAsPaid' : IDL.Func([IDL.Text], [], []),
    'markBookingAsUnpaid' : IDL.Func([IDL.Text], [], []),
    'markTimeSlotUnavailable' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveExtendedProfile' : IDL.Func([IDL.Principal, ExtendedProfile], [], []),
    'saveLifestyleSurveyResult' : IDL.Func([LifestyleSurveyResult], [], []),
    'setAboutMeContent' : IDL.Func([IDL.Text], [], []),
    'setCoachProfilePicture' : IDL.Func([ExternalBlob], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unmarkTimeSlotUnavailable' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateDonationOption' : IDL.Func([DonationOption], [], []),
    'updateGym' : IDL.Func([Gym], [], []),
    'updateWorkoutProgram' : IDL.Func([WorkoutProgram], [], []),
  });
};

export const init = ({ IDL }) => { return []; };