/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DonationOption {
    id: string;
    method: string;
    details: string;
}
export interface TimeSlot {
    isUnavailable: boolean;
    date: string;
    time: string;
    isBooked: boolean;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface LifestyleSurveyResult {
    id: string;
    recommendations: Array<string>;
    summaryMessage: string;
    score: bigint;
    category: string;
}
export interface BodyAnalysisSummary {
    recommendations: string;
    muscleMassEstimate: number;
    score: bigint;
    bodyType: BodyType;
    bodyFatPercentage: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface AboutMeContent {
    content: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ExtendedProfile {
    age: bigint;
    bmi: number;
    weight: bigint;
    height: bigint;
    lSit: bigint;
    squats: bigint;
    pullUps: bigint;
    pushUps: bigint;
    gender: string;
    details: string;
    bodyFatPercentage: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface GalleryImage {
    id: string;
    description: string;
    image: ExternalBlob;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Gym {
    id: string;
    name: string;
    address: string;
    details: string;
}
export interface Booking {
    id: string;
    healthInformation: string;
    date: string;
    time: string;
    user: Principal;
    isPaid: boolean;
    gymId: string;
    healthDisclosureAccepted: boolean;
    programId: string;
}
export interface WorkoutProgram {
    id: string;
    title: string;
    description: string;
    image?: ExternalBlob;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface UserProfile {
    contactInfo: string;
    aboutMe: string;
    name: string;
    recentTrainings: Array<string>;
    isPublic: boolean;
    avatar?: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BodyType {
    endomorph = "endomorph",
    mesomorph = "mesomorph",
    ectomorph = "ectomorph"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addDonationOption(option: DonationOption): Promise<void>;
    addGalleryImage(image: GalleryImage): Promise<void>;
    addGym(gym: Gym): Promise<void>;
    addWorkoutProgram(program: WorkoutProgram): Promise<void>;
    analyzeBodyShape(fileId: string, analysis: BodyAnalysisSummary): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBooking(booking: Booking): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteAnalysisResult(fileId: string): Promise<void>;
    deleteBooking(bookingId: string): Promise<void>;
    deleteDonationOption(optionId: string): Promise<void>;
    deleteGalleryImage(imageId: string): Promise<void>;
    deleteGym(gymId: string): Promise<void>;
    deleteLifestyleSurveyResult(resultId: string): Promise<void>;
    deleteWorkoutProgram(programId: string): Promise<void>;
    getAboutMeContent(): Promise<AboutMeContent | null>;
    getAllAnalysisResults(): Promise<Array<BodyAnalysisSummary>>;
    getAllLifestyleSurveyResults(): Promise<Array<LifestyleSurveyResult>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getAnalysisResult(fileId: string): Promise<BodyAnalysisSummary | null>;
    getAvailableTimeSlots(date: string): Promise<Array<TimeSlot>>;
    getBookings(): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoachProfilePicture(): Promise<ExternalBlob | null>;
    getDonationOptions(): Promise<Array<DonationOption>>;
    getExtendedProfile(user: Principal): Promise<ExtendedProfile | null>;
    getGalleryImages(): Promise<Array<GalleryImage>>;
    getGyms(): Promise<Array<Gym>>;
    getLifestyleSurveyResult(resultId: string): Promise<LifestyleSurveyResult | null>;
    getLikeCount(): Promise<bigint>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkoutPrograms(): Promise<Array<WorkoutProgram>>;
    hasCallerLiked(): Promise<boolean>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    likeWebsite(): Promise<void>;
    markBookingAsPaid(bookingId: string): Promise<void>;
    markBookingAsUnpaid(bookingId: string): Promise<void>;
    markTimeSlotUnavailable(date: string, time: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveExtendedProfile(user: Principal, profile: ExtendedProfile): Promise<void>;
    saveLifestyleSurveyResult(result: LifestyleSurveyResult): Promise<void>;
    setAboutMeContent(content: string): Promise<void>;
    setCoachProfilePicture(image: ExternalBlob): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unmarkTimeSlotUnavailable(date: string, time: string): Promise<void>;
    updateDonationOption(option: DonationOption): Promise<void>;
    updateGym(gym: Gym): Promise<void>;
    updateWorkoutProgram(program: WorkoutProgram): Promise<void>;
}
import type { AboutMeContent as _AboutMeContent, BodyAnalysisSummary as _BodyAnalysisSummary, BodyType as _BodyType, ExtendedProfile as _ExtendedProfile, ExternalBlob as _ExternalBlob, GalleryImage as _GalleryImage, LifestyleSurveyResult as _LifestyleSurveyResult, StripeSessionStatus as _StripeSessionStatus, UserProfile as _UserProfile, UserRole as _UserRole, WorkoutProgram as _WorkoutProgram, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addDonationOption(arg0: DonationOption): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDonationOption(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDonationOption(arg0);
            return result;
        }
    }
    async addGalleryImage(arg0: GalleryImage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryImage(await to_candid_GalleryImage_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryImage(await to_candid_GalleryImage_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addGym(arg0: Gym): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGym(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGym(arg0);
            return result;
        }
    }
    async addWorkoutProgram(arg0: WorkoutProgram): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkoutProgram(await to_candid_WorkoutProgram_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkoutProgram(await to_candid_WorkoutProgram_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async analyzeBodyShape(arg0: string, arg1: BodyAnalysisSummary): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeBodyShape(arg0, to_candid_BodyAnalysisSummary_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeBodyShape(arg0, to_candid_BodyAnalysisSummary_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBooking(arg0: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteAnalysisResult(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnalysisResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnalysisResult(arg0);
            return result;
        }
    }
    async deleteBooking(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async deleteDonationOption(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDonationOption(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDonationOption(arg0);
            return result;
        }
    }
    async deleteGalleryImage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryImage(arg0);
            return result;
        }
    }
    async deleteGym(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGym(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGym(arg0);
            return result;
        }
    }
    async deleteLifestyleSurveyResult(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLifestyleSurveyResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLifestyleSurveyResult(arg0);
            return result;
        }
    }
    async deleteWorkoutProgram(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkoutProgram(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkoutProgram(arg0);
            return result;
        }
    }
    async getAboutMeContent(): Promise<AboutMeContent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAboutMeContent();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAboutMeContent();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAnalysisResults(): Promise<Array<BodyAnalysisSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnalysisResults();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnalysisResults();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLifestyleSurveyResults(): Promise<Array<LifestyleSurveyResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLifestyleSurveyResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLifestyleSurveyResults();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalysisResult(arg0: string): Promise<BodyAnalysisSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysisResult(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysisResult(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableTimeSlots(arg0: string): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableTimeSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableTimeSlots(arg0);
            return result;
        }
    }
    async getBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoachProfilePicture(): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoachProfilePicture();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoachProfilePicture();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonationOptions(): Promise<Array<DonationOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationOptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationOptions();
            return result;
        }
    }
    async getExtendedProfile(arg0: Principal): Promise<ExtendedProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExtendedProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExtendedProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImages();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImages();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGyms(): Promise<Array<Gym>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGyms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGyms();
            return result;
        }
    }
    async getLifestyleSurveyResult(arg0: string): Promise<LifestyleSurveyResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLifestyleSurveyResult(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLifestyleSurveyResult(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLikeCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikeCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikeCount();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutPrograms(): Promise<Array<WorkoutProgram>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutPrograms();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutPrograms();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasCallerLiked(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasCallerLiked();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasCallerLiked();
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async likeWebsite(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeWebsite();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeWebsite();
            return result;
        }
    }
    async markBookingAsPaid(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markBookingAsPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markBookingAsPaid(arg0);
            return result;
        }
    }
    async markBookingAsUnpaid(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markBookingAsUnpaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markBookingAsUnpaid(arg0);
            return result;
        }
    }
    async markTimeSlotUnavailable(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTimeSlotUnavailable(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTimeSlotUnavailable(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n46(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveExtendedProfile(arg0: Principal, arg1: ExtendedProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveExtendedProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveExtendedProfile(arg0, arg1);
            return result;
        }
    }
    async saveLifestyleSurveyResult(arg0: LifestyleSurveyResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLifestyleSurveyResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLifestyleSurveyResult(arg0);
            return result;
        }
    }
    async setAboutMeContent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAboutMeContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAboutMeContent(arg0);
            return result;
        }
    }
    async setCoachProfilePicture(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCoachProfilePicture(await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCoachProfilePicture(await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unmarkTimeSlotUnavailable(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unmarkTimeSlotUnavailable(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unmarkTimeSlotUnavailable(arg0, arg1);
            return result;
        }
    }
    async updateDonationOption(arg0: DonationOption): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonationOption(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonationOption(arg0);
            return result;
        }
    }
    async updateGym(arg0: Gym): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGym(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGym(arg0);
            return result;
        }
    }
    async updateWorkoutProgram(arg0: WorkoutProgram): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkoutProgram(await to_candid_WorkoutProgram_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkoutProgram(await to_candid_WorkoutProgram_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BodyAnalysisSummary_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BodyAnalysisSummary): BodyAnalysisSummary {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_BodyType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BodyType): BodyType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryImage_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryImage): Promise<GalleryImage> {
    return await from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_WorkoutProgram_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutProgram): Promise<WorkoutProgram> {
    return await from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AboutMeContent]): AboutMeContent | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BodyAnalysisSummary]): BodyAnalysisSummary | null {
    return value.length === 0 ? null : from_candid_BodyAnalysisSummary_n21(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExtendedProfile]): ExtendedProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LifestyleSurveyResult]): LifestyleSurveyResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recommendations: string;
    muscleMassEstimate: number;
    score: bigint;
    bodyType: _BodyType;
    bodyFatPercentage: bigint;
}): {
    recommendations: string;
    muscleMassEstimate: number;
    score: bigint;
    bodyType: BodyType;
    bodyFatPercentage: bigint;
} {
    return {
        recommendations: value.recommendations,
        muscleMassEstimate: value.muscleMassEstimate,
        score: value.score,
        bodyType: from_candid_BodyType_n23(_uploadFile, _downloadFile, value.bodyType),
        bodyFatPercentage: value.bodyFatPercentage
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: string;
    aboutMe: string;
    name: string;
    recentTrainings: Array<string>;
    isPublic: boolean;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    contactInfo: string;
    aboutMe: string;
    name: string;
    recentTrainings: Array<string>;
    isPublic: boolean;
    avatar?: ExternalBlob;
}> {
    return {
        contactInfo: value.contactInfo,
        aboutMe: value.aboutMe,
        name: value.name,
        recentTrainings: value.recentTrainings,
        isPublic: value.isPublic,
        avatar: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.avatar))
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    description: string;
    image: _ExternalBlob;
}): Promise<{
    id: string;
    description: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        description: value.description,
        image: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.image)
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
async function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    title: string;
    description: string;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        image: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endomorph: null;
} | {
    mesomorph: null;
} | {
    ectomorph: null;
}): BodyType {
    return "endomorph" in value ? BodyType.endomorph : "mesomorph" in value ? BodyType.mesomorph : "ectomorph" in value ? BodyType.ectomorph : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n41(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BodyAnalysisSummary>): Array<BodyAnalysisSummary> {
    return value.map((x)=>from_candid_BodyAnalysisSummary_n21(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n26(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryImage>): Promise<Array<GalleryImage>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryImage_n36(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutProgram>): Promise<Array<WorkoutProgram>> {
    return await Promise.all(value.map(async (x)=>await from_candid_WorkoutProgram_n44(_uploadFile, _downloadFile, x)));
}
function to_candid_BodyAnalysisSummary_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BodyAnalysisSummary): _BodyAnalysisSummary {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_BodyType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BodyType): _BodyType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_GalleryImage_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryImage): Promise<_GalleryImage> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_WorkoutProgram_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutProgram): Promise<_WorkoutProgram> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    image?: ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    description: string;
    image: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image)) : candid_none()
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recommendations: string;
    muscleMassEstimate: number;
    score: bigint;
    bodyType: BodyType;
    bodyFatPercentage: bigint;
}): {
    recommendations: string;
    muscleMassEstimate: number;
    score: bigint;
    bodyType: _BodyType;
    bodyFatPercentage: bigint;
} {
    return {
        recommendations: value.recommendations,
        muscleMassEstimate: value.muscleMassEstimate,
        score: value.score,
        bodyType: to_candid_BodyType_n15(_uploadFile, _downloadFile, value.bodyType),
        bodyFatPercentage: value.bodyFatPercentage
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: string;
    aboutMe: string;
    name: string;
    recentTrainings: Array<string>;
    isPublic: boolean;
    avatar?: ExternalBlob;
}): Promise<{
    contactInfo: string;
    aboutMe: string;
    name: string;
    recentTrainings: Array<string>;
    isPublic: boolean;
    avatar: [] | [_ExternalBlob];
}> {
    return {
        contactInfo: value.contactInfo,
        aboutMe: value.aboutMe,
        name: value.name,
        recentTrainings: value.recentTrainings,
        isPublic: value.isPublic,
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    description: string;
    image: ExternalBlob;
}): Promise<{
    id: string;
    description: string;
    image: _ExternalBlob;
}> {
    return {
        id: value.id,
        description: value.description,
        image: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.image)
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BodyType): {
    endomorph: null;
} | {
    mesomorph: null;
} | {
    ectomorph: null;
} {
    return value == BodyType.endomorph ? {
        endomorph: null
    } : value == BodyType.mesomorph ? {
        mesomorph: null
    } : value == BodyType.ectomorph ? {
        ectomorph: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
